### ISSUE TITLE
How to block email with status Suspicious ?

### ISSUE THREAD

**Issue by marshmeloo** [CleanTalk/yii2-antispam#2]

**Comment by CleanTalk** [comment]
I am sorry, right now the API doesn't have any option to mark suspicious emails. We don't provide any information about that status to avoid false/positive issues.

Could you please provide us an example of suspicious email that you need to block?

Thank you!

**Comment by marshmeloo** [comment]
Below are some of suspicious email from which we are getting spam.

https://cleantalk.org/blacklists?record=ibaaggeva@dfoofmail.com
https://cleantalk.org/blacklists?record=eucave@asdooeemail.com
https://cleantalk.org/blacklists?record=adawakig@dfoofmail.com
https://cleantalk.org/blacklists?record=olalugow@mailasdkr.com
https://cleantalk.org/blacklists?record=ibaaggeva@dfoofmail.com
https://cleantalk.org/blacklists?record=acurmos@asooemail.net
https://cleantalk.org/blacklists?record=ajajex@asooemail.com
https://cleantalk.org/blacklists?record=ipuxoy@mailasdkr.com
https://cleantalk.org/blacklists?record=orazuiyap@asooemail.net

These are just few, we are getting many more day by day.

**Comment by CleanTalk** [comment]
Thank you for examples!

We don't have spam history for these addresses, i.e. these addresses were not any spam activity on other websites. That's why service didn't block them.

Did you have missed spam with CleanTalk with any email from that list? If you did, please let me know the email address. I will check our logs. Actually, CleanTalk has several test to detect spam, so even an email not in the blacklists it can stop most of spam comments/registrations.

Thank you!

**Comment by marshmeloo** [comment]
I'm little confused, as cleantalk did show these email address as suspicious (see in the attached image)
![4](https://cloud.githubusercontent.com/assets/9282082/11063564/92e9161c-87dd-11e5-8ae7-3a766eb64e7e.PNG)

also mentioned "asdooeemail.com recently detected spam active addresses"
Attacked site 10,48 etc

The above email's before cleantalk. We have applied cleantalk today on my site, will test for week. So if we get any spam, will definitely inform you right away.

**Comment by CleanTalk** [comment]
The Suspicious status means that the email might be blocked, but it doesn't obligatory. Final decision depends on results of other anti-spam tests. 

To test protection please use any email with Blacklisted status,

https://cleantalk.org/blacklists/top20

"asdooeemail.com" is an email hosting, so we collect some information about spam activity per hosting. But doesn't use it for strict filtration, because strict filtration only by hosting will be rise false/positive rate. 

Thank you!
